### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by HyphenMaster** [PrinterLUA/FORGOTTENSERVER-ORTS#1536]
- Too much looted items in Ferumbras (all possible),
- Questlog is not updated when you get Necro task from NPC Lugri,
- Wrong message with NPC Grizzly Adams when you say "tasks": (18:28 Grizzly Adams: The current tasks that you can choose are Hydras, Medusae, Behemoths, Sea Serpents and Young Sea Serpents, Hellhounds, Ghastly Dragons, Destroyers, Undead Dragons and **Necromancers** and **Priestess**.),
- When you Cancel task Questlog is not updated

**Comment by att3** [comment]
When you Cancel task Questlog is not updated -> 
player:setStorageValue(QUESTSTORAGE_BASE + cancel[cid], -1)
player:setStorageValue(KILLSSTORAGE_BASE + cancel[cid], -1)
= should disappear from questlog.
However I noticed that when you "report" a task it makes the storage id 0 instead of -1 which means that you still have the questlog.

Well, honestly I think that whole killing in the name of.. should be rewritten~. 

Not sure if we can have the questlog as in RL though.
Atm:
<mission="Paw and Fur: rats" storageid="123" description="You have killed |STATE|/10 rats."/>
After you report the task to Grizzly the mission will disappear from you questlog.

Instead of;
<mission="Paw and Fur: rats" storageid="123" id="10" description="You have killed |STATE|/10 rats."/>
<mission="Paw and Fur: rats" storageid="123" id="11" description="You have killed 10 rats. You can restart this task."/>


Well, regarding to killing in the name of.. I don't think that questlog is major issue.
Grizzly should act a bit differently, more like this:
http://otland.net/threads/creatureevent-npc-killing-in-the-name-of.122701/
(2nd post)

Mostly talking about the messages. (e.g after you say "hydras" Grizzly will tell you about them "custom msg" and ask if you want to slain 650 hydras) instead of ("Do you want to slain (KILL_AMOUNT) (MONSTER_NAME)?")
> Bonus point system. 
> Correct msgs(everything?)
> "promotion system"
> Some questlog rewriting (regarding to this)

I was about to thought about rewriting the file but I quickly realized that it goes beyond my skills and it would require shit loads of work, therefore I tried to merge the current system with  that script cyko posted on OTland. 
- Grizzly: http://pastebin.com/PMqEu8Da
- lib http://pastebin.com/4auWG94B (some minor changes e.g boss msg)
It's not done yet, but I been thinking does the file need rewriting after all.
I know it would be easier to make it fit the real tibia one without rewriting the file but I also know that it would look horrible. (does already)
I know it's massive job, specially for someone like me who is not good with LUA yet.
But then again e.g adding more functions I believe the file could look better.

Quoting @TheSumm here:Grizzly Adams should be completly rewritten to fit the real tibia one.
https://github.com/PrinterLUA/FORGOTTENSERVER-ORTS/issues/1016

So I am going to ask:
1. Should I rewrite the NPC file. (can't guarantee that it would look much better)
2. Continue on "editing it as on RL, adding more functions to make it look cleaner"
3. Or is somebody else interested in re-writing this?

Might be worth of mentioning that currently I do not have a real-tibia character so the messages won't always be 100% correct/up to date, though I can find most messages from youtube and tibiawikia.

**Comment by EPuncker** [comment]
ferumbras is fine because the rates are adjusted for a server with 1x loot rate, if you want it to not drop more items than expected just edit the file for your own server :)
